server:
  port: 8082
spring:
  application:
    name: portfolio-server
  cloud:
    stream:
      bindings:
        input:
          destination: instruction
          group: portfolio
          content-type: application/json